[build]
  command = "npm install"

[deploy]
  command = "npm start"

[[services]]
[services.variables]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"